//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<course_tble> course_tble { get; set; }
        public virtual DbSet<gaurdian_tbl> gaurdian_tbl { get; set; }
        public virtual DbSet<payment_tbl> payment_tbl { get; set; }
        public virtual DbSet<status_tbl> status_tbl { get; set; }
        public virtual DbSet<student_tbl> student_tbl { get; set; }
        public virtual DbSet<teacher_tbl> teacher_tbl { get; set; }
        public virtual DbSet<user_tbl> user_tbl { get; set; }
    }
}
