//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_tble
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public course_tble()
        {
            this.student_tbl = new HashSet<student_tbl>();
        }
    
        public int CourseId { get; set; }
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> CourseDuration { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual status_tbl status_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student_tbl> student_tbl { get; set; }
    }
}
