//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_tbl
    {
        public int PaymentId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<double> Amount { get; set; }
        public System.DateTime CaptureDate { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual student_tbl student_tbl { get; set; }
        public virtual user_tbl user_tbl { get; set; }
    }
}
