//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student_tbl()
        {
            this.gaurdian_tbl = new HashSet<gaurdian_tbl>();
            this.payment_tbl = new HashSet<payment_tbl>();
        }
    
        public int StudentId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Gender { get; set; }
        public string Cell { get; set; }
        public string Email { get; set; }
        public string PostallAddress { get; set; }
        public Nullable<int> Semester { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual course_tble course_tble { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gaurdian_tbl> gaurdian_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment_tbl> payment_tbl { get; set; }
        public virtual status_tbl status_tbl { get; set; }
    }
}
